export interface Intervention { id: string; label: string; layer: 1 | 2 | 3 | 4 | 5 | 6; short: string; inputs: string[]; efforts: string[]; outputs: string[] }
export interface Connection { from: string; to: string; label: string }

// INTERVENTIONS and CONNECTIONS are copied verbatim from _legacy/js/network.js.
export const INTERVENTIONS: Intervention[] = [
  { id: "1a", label: "Venture Registry", layer: 1, short: "Registry",
    inputs: ["Companies House data", "Patent filings", "Funding announcements", "Hiring signals", "Publications", "KYC/credential infrastructure"],
    efforts: ["Data ingestion pipelines", "Entity resolution", "Continuous monitoring", "Identity verification"],
    outputs: ["Live ecosystem map", "Verified entity profiles", "Longitudinal venture data", "Training data for AI"] },
  { id: "1b", label: "Needs-Offers Matching", layer: 1, short: "Matching",
    inputs: ["Venture Registry data", "Investor mandate data", "Talent pool data", "Needs/offers signals"],
    efforts: ["Signal inference from activity", "Matching algorithms", "Recommendation ranking"],
    outputs: ["Matched pairs", "Gap analysis", "Demand signals"] },
  { id: "1c", label: "Network Diagnostics", layer: 1, short: "Diagnostics",
    inputs: ["Venture Registry data", "Matching interaction data", "Deal outcome data", "Membership data"],
    efforts: ["Centrality analysis", "Structural hole detection", "Community clustering", "Health scoring"],
    outputs: ["Ecosystem health dashboard", "Bottleneck identification", "Intervention targeting", "Benchmarking data"] },
  { id: "1d", label: "Sector Emergence", layer: 1, short: "Emergence",
    inputs: ["Patent co-filing data", "Hiring clusters", "Publication co-authorship", "Venture Registry data"],
    efforts: ["Pattern detection models", "Anomaly detection", "Trend forecasting"],
    outputs: ["Emerging sector alerts", "Diversification opportunities", "Investment signal data"] },
  { id: "2a", label: "Governance Routing", layer: 2, short: "GovRoute",
    inputs: ["Venture profiles", "Regulatory text corpora", "Growth stage data", "Jurisdiction data"],
    efforts: ["NLP regulatory parsing", "ROI optimisation", "Roadmap generation", "Stage-matching"],
    outputs: ["Prioritised roadmaps", "Cost-of-non-compliance estimates", "Pre-certification status", "Governance training data"] },
  { id: "2b", label: "Contract & Procurement", layer: 2, short: "Contracts",
    inputs: ["Deal type data", "Governance routing output", "Template libraries", "Payment infrastructure"],
    efforts: ["AI contract drafting", "Vendor assessment automation", "Pre-certification"],
    outputs: ["Standardised instruments", "Pre-certified ventures", "Compressed procurement", "Contract outcome data"] },
  { id: "2c", label: "Financial Ops Auto", layer: 2, short: "FinOps",
    inputs: ["Cap table data", "SEIS/EIS parameters", "Grant reporting reqs", "Invoice data"],
    efforts: ["Automated invoicing", "Tax credit processing", "Grant compliance reporting"],
    outputs: ["Clean financial records", "Optimised tax claims", "Freed founder time", "Financial performance data"] },
  { id: "3a", label: "Deal Flow Matching", layer: 3, short: "DealFlow",
    inputs: ["Venture Registry data", "Investor mandates", "Matching engine output", "Pre-certification status"],
    efforts: ["Continuous mandate matching", "Proactive surfacing", "Cross-hub routing"],
    outputs: ["Matched investment targets", "Deal pipeline", "Capital deployment data"] },
  { id: "3b", label: "Dynamic Fund Structuring", layer: 3, short: "Struct",
    inputs: ["SEIS/EIS parameters", "Investor profiles", "Deal flow data", "Tax regime data"],
    efforts: ["Vehicle optimisation modelling", "Tax arbitrage calc", "Regulatory compliance"],
    outputs: ["Optimised fund structures", "SEIS-maximised vehicles", "Exportable structuring tools"] },
  { id: "3c", label: "IP Valuation Engine", layer: 3, short: "IPValue",
    inputs: ["Longitudinal data", "Patent networks", "Academic impact", "Team data", "Comparable transactions"],
    efforts: ["Multimodal model training", "Valuation model dev", "Backtesting"],
    outputs: ["Defensible IP valuations", "Rating methodology", "New asset class creation", "Exportable tool"] },
  { id: "3d", label: "Value Retention Instruments", layer: 3, short: "ValRetain",
    inputs: ["Deal outcome data", "Cooperative legal frameworks", "Exit event data", "Fund structuring output"],
    efforts: ["Instrument design", "Legal structuring", "Ecosystem equity management"],
    outputs: ["Stakeholdership via exits", "Retained value pool", "Recycled capital"] },
  { id: "3e", label: "Parametric Insurance", layer: 3, short: "Insurance",
    inputs: ["Sensing data", "Risk event triggers", "Venture profile data", "Commodity feed"],
    efforts: ["Risk model development", "Trigger calibration", "Claims automation", "Premium pricing"],
    outputs: ["Innovation risk coverage", "Automated payouts", "Risk-pooled portfolio", "Premium income"] },
  { id: "3f", label: "Cross-Hub Co-Investment", layer: 3, short: "CoInvest",
    inputs: ["Hub partnership agreements", "Cross-jurisdiction data", "Deal flow from hubs"],
    efforts: ["Vehicle structuring", "Automated compliance", "Co-investment routing"],
    outputs: ["Bilateral investment flows", "Connectivity infrastructure", "Cross-hub deal data"] },
  { id: "4a", label: "Hub-to-Hub Partnerships", layer: 4, short: "HubPartner",
    inputs: ["Sensing intelligence", "Complementary capability data", "Regulatory compatibility", "Co-invest infrastructure"],
    efforts: ["Partnership negotiation", "Term sheet design", "Governance alignment"],
    outputs: ["Bilateral agreements", "Shared sensing data", "Co-investment routing"] },
  { id: "4b", label: "Institutional Campaigns", layer: 4, short: "Campaign",
    inputs: ["Stakeholder maps", "Policy models", "Health data", "Evidential base"],
    efforts: ["Lobbying", "Governance navigation", "Narrative construction"],
    outputs: ["Policy changes", "Academic pathways", "Institutional funding"] },
  { id: "4c", label: "Anchor Tenant Recruitment", layer: 4, short: "Anchors",
    inputs: ["Corporate strategy signals", "Sensing data", "Pre-certified ventures", "Value models"],
    efforts: ["Targeted outreach", "Incentive package design", "Relationship cultivation"],
    outputs: ["Corporate presence", "Anchor investment", "Market access", "Demand signal"] },
  { id: "4d", label: "Geopolitical Intelligence", layer: 4, short: "GeoPol",
    inputs: ["Geopolitical data feeds", "Trade restriction mon", "Regulatory divergence", "Sensing layer data"],
    efforts: ["AI analysis", "Sovereignty risk assessment", "Opportunity ID"],
    outputs: ["Risk reports", "Dealmaking intelligence", "Exportable intelligence"] },
  { id: "5a", label: "Financial Sustainability", layer: 5, short: "FinSustain",
    inputs: ["Revenue flows", "Membership fees", "Transaction fees", "Insurance premiums", "Data sales"],
    efforts: ["Revenue collection", "Cost management", "Reinvestment allocation", "Export pricing"],
    outputs: ["Operational funding", "Reinvestment surplus", "Exportable business model"] },
  { id: "6a", label: "Training Data Creation", layer: 6, short: "TrainData",
    inputs: ["All operational data", "Venture trajectories", "Deal outcomes", "Governance decisions"],
    efforts: ["Data labelling", "Quality assurance", "Privacy-preserving aggregation"],
    outputs: ["Labelled training sets", "Longitudinal corpus", "Unique data asset"] },
  { id: "6b", label: "AI Research Demand Pull", layer: 6, short: "Research",
    inputs: ["Unsolved problems", "Training data", "Cambridge AI research capacity"],
    efforts: ["Problem specification", "Research mapping", "Model development"],
    outputs: ["New AI models", "Published research", "Layer performance improvements"] },
  { id: "6d", label: "Ecosystem Control Mechanism", layer: 6, short: "EcoControl",
    inputs: ["Integrated layer data", "Health diagnostics", "Custom AI models"],
    efforts: ["Control model training", "Real-time coordination", "Anomaly response"],
    outputs: ["Coordinated ecosystem", "Automated orchestration", "Cambridge-native AI"] },
  { id: "6e", label: "Innovation Prediction Model", layer: 6, short: "Predict",
    inputs: ["5+ years longitudinal data", "All layer outputs", "External benchmarks"],
    efforts: ["Foundational model training", "Validation", "Calibration"],
    outputs: ["Probability distributions", "Portfolio construction tool", "Globally exportable product"] }
];

export const CONNECTIONS: Connection[] = [
  { from: "1a", to: "1b", label: "entity data" }, { from: "1a", to: "1c", label: "entity data" },
  { from: "1a", to: "1d", label: "entity data" }, { from: "1a", to: "2a", label: "venture profiles" },
  { from: "1a", to: "3a", label: "venture data" }, { from: "1a", to: "3c", label: "longitudinal data" },
  { from: "1a", to: "3e", label: "venture profiles" }, { from: "1a", to: "4c", label: "venture data" },
  { from: "1a", to: "6a", label: "raw data" },
  { from: "1b", to: "1c", label: "interaction data" }, { from: "1b", to: "3a", label: "matched pairs" },
  { from: "1b", to: "4a", label: "capability analysis" },
  { from: "1c", to: "4a", label: "health data" }, { from: "1c", to: "4b", label: "evidential base" },
  { from: "1c", to: "6d", label: "health metrics" },
  { from: "1d", to: "3b", label: "sector signals" }, { from: "1d", to: "4b", label: "diversification data" },
  { from: "2a", to: "2b", label: "compliance status" }, { from: "2a", to: "3a", label: "pre-certification" },
  { from: "2a", to: "3f", label: "jurisdictional data" },
  { from: "2b", to: "3a", label: "instruments" }, { from: "2b", to: "4a", label: "inter-hub templates" },
  { from: "2c", to: "3b", label: "financial data" }, { from: "2c", to: "5a", label: "clean records" },
  { from: "3a", to: "3b", label: "deal pipeline" }, { from: "3a", to: "3d", label: "deal outcomes" },
  { from: "3a", to: "5a", label: "transaction fees" }, { from: "3a", to: "6a", label: "deal data" },
  { from: "3b", to: "3f", label: "vehicle structures" }, { from: "3b", to: "5a", label: "structuring fees" },
  { from: "3c", to: "3a", label: "valuations" }, { from: "3c", to: "3e", label: "risk assessments" },
  { from: "3c", to: "5a", label: "valuation revenue" },
  { from: "3d", to: "5a", label: "recycled capital" },
  { from: "3e", to: "1a", label: "risk event data" }, { from: "3e", to: "5a", label: "premium income" },
  { from: "3f", to: "4a", label: "bilateral flows" }, { from: "3f", to: "5a", label: "vehicle fees" },
  { from: "4a", to: "1a", label: "new hub data" }, { from: "4a", to: "3f", label: "partnership terms" },
  { from: "4b", to: "2a", label: "policy changes" }, { from: "4b", to: "3b", label: "expanded SEIS/EIS" },
  { from: "4c", to: "1a", label: "new entities" }, { from: "4c", to: "3a", label: "investment demand" },
  { from: "4c", to: "5a", label: "anchor fees" },
  { from: "5a", to: "1a", label: "operational funding" }, { from: "5a", to: "2a", label: "operational funding" },
  { from: "5a", to: "6a", label: "operational funding" },
  { from: "6a", to: "6b", label: "training sets" }, { from: "6a", to: "6d", label: "training data" },
  { from: "6a", to: "6e", label: "longitudinal corpus" },
  { from: "6b", to: "1b", label: "improved models" }, { from: "6b", to: "2a", label: "improved NLP" },
  { from: "6b", to: "3c", label: "improved valuation" },
  { from: "6d", to: "1a", label: "coordination signals" }, { from: "6d", to: "5a", label: "optimisation" },
  { from: "6e", to: "5a", label: "product revenue" }, { from: "6e", to: "4a", label: "dealmaking intelligence" }
];

export const LAYERS = [
  { n: 1, name: 'Sensing', color: '#3B82F6' },
  { n: 2, name: 'Operations', color: '#10B981' },
  { n: 3, name: 'Capital', color: '#F59E0B' },
  { n: 4, name: 'Dealmaking', color: '#EF4444' },
  { n: 5, name: 'Sustainability', color: '#8B5CF6' },
  { n: 6, name: 'AI Generation', color: '#EC4899' },
] as const;

export const layerColor = (layer: number) => LAYERS.find((l) => l.n === layer)?.color ?? '#0e0e10';
export const layerName = (layer: number) => LAYERS.find((l) => l.n === layer)?.name ?? '';

export function toGraphData() {
  return {
    nodes: INTERVENTIONS.map(({ id, label, layer, short }) => ({ id, label, layer, short })),
    links: CONNECTIONS.map(({ from, to, label }) => ({ source: from, target: to, label })),
  };
}
